### ISSUE TITLE
possible to use without density values?

### ISSUE THREAD

**Issue by max-mapper** [mikolalysenko/isosurface#1]
Hi Mikola,

I noticed that the meshers here assume each point in the input volumetric data contains a density field value. In the voxel.js worlds i've been working with I only have a binary in/out value (I think). Do you know how I can smooth an arbitrary cubic volume of voxels given the values at each point are binary rather than density? Or is there some method for calculating density?

Thanks,

Max

**Comment by max-mapper** [comment]
ahh, I figured it out. i'm now just passing 0 if its a point or -1 if it isn't. here is a sphere rendered with the original points in white and the surface net in red:

![Screen Shot 2013-02-02 at 7 35 47 PM](https://f.cloud.github.com/assets/39759/121538/1a841b82-6db3-11e2-921f-6cedde446de5.png)

**Comment by mikolalysenko** [comment]
Alright, let me know if you need anything else.  Though if you just want to create a smooth mesh you probably will have to specify the isosurface densities somehow.

**Comment by max-mapper** [comment]
if you wouldn't mind elaborating a little on how that might work I would love to hear. I was naively thinking that if for every chunk I sent a 1 voxel buffer in addition to the chunk itself then at least the meshes would overlap, though they wouldn't be smooth because of protrusions like this:

![Screen Shot 2013-02-03 at 6 43 09 PM](https://f.cloud.github.com/assets/39759/122608/d1ce9ae4-6e74-11e2-8ddd-407b2e930569.png)

**Comment by max-mapper** [comment]
p.s. the code that produced that shot is here http://voxel-creator.jit.su/4700570 hit `Play`

**Comment by mikolalysenko** [comment]
Hmm...  I can't seem to view the code since I am on an airplane right now and it keeps saying "ECONNRESET" when I try to view it.  I'll give it another shot later.  As an off-the-cuff guess, I'd say it looks like you have some sort of off-by-one error with the chunk boundary.
