### ISSUE TITLE
output data seems to be inverted?

### ISSUE THREAD

**Issue by max-mapper** [mikolalysenko/isosurface#2]
if I take the output of the surface net algorithm here and put it into .stl and render it, it shows up as inside out:

![screen shot 2013-08-13 at 11 59 02 pm](https://f.cloud.github.com/assets/39759/960188/16541740-04af-11e3-9ef6-cb4ca930021b.png)

however, if I load the same exact data into your isosurface toolbox (which has material.doubleSided = true) it looks okay

![screen shot 2013-08-13 at 11 57 55 pm](https://f.cloud.github.com/assets/39759/960189/23697042-04af-11e3-994b-4f1a83de5050.png)

do you know what's going on here and how I might get normal looking .stls?

**Comment by mikolalysenko** [comment]
That is a convention that your renderer has to decide on.  If you want the facets in a different order, just swap two vertices in each of the faces.

**Comment by mikolalysenko** [comment]
Or alternatively you could change the sign of the implicit function you are using.
